schema_version = "1.0.0"

id = "copy_object_name_to_data"
version = "1.1.1"
name = "Copy Object Name to Data"
tagline = "A simple operator to copy object names to object data"
maintainer = "Xury Greer <xury.greer@gmail.com>"
type = "add-on"
website = "https://github.com/Xury46/copy-object-name-to-data"
tags = ["Object", "User Interface"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
